project:
  type: website

  
  render:
    - index.qmd
    - requirements.qmd
    - requirements/*.qmd

filters:
  - accreditation
  - quarto

website:
  title: "5th-Year Reaffirmation"
  page-navigation: true
  back-to-top-navigation: true 
  search: false
  page-footer: 
    left: 
      - text: College Home Page
        href: https://www.college.edu/
        target: _blank
  
  sidebar:
    - title: "Home"
      style: "docked"
      background: dark
      contents:
        - section: "Home" 
          contents: 
            - index.qmd

    - title: "Requirements"
      contents:
        - requirements.qmd
        - requirements/Standard 05.4.qmd
        
  navbar:
    background: dark
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Requirements"
        href: requirements.qmd
        
format:
  html:
    toc: true
    toc-expand: true 
    quarto-required: ">=1.4.0"
