# Standard 5.4

::: {custom-style="Subtitle"}
Qualified Administrative/Academic Officers
:::

::: {custom-style="Abstract"}
The institution employs and regularly evaluates administrative and
academic officers with appropriate experience and qualifications to lead
the institution.
:::

## Judgment

[☒ Compliant ☐ Non-Compliant ☐ Not Applicable]{custom-style="Judgment"}

## Narrative

::: {custom-style="Body Text"}
This is my narrative.
:::

<table>
<colgroup>
<col style="width: 19%" />
<col style="width: 28%" />
<col style="width: 22%" />
<col style="width: 29%" />
</colgroup>
<thead>
<tr class="header">
<th>Name/Title</th>
<th>Responsibilities</th>
<th>Academic Preparation</th>
<th>Professional Experience</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p><span data-custom-style="Link to Artifact - Resume">Dr. Person
One</span></p>
<p><span
data-custom-style="Link to Artifact - Job Description">President</span></p></td>
<td>Provides leadership and overall management of HCC and its associated
entities under the policies, rules, and regulations of the Board of
Trustees, the State Board of Community Colleges, the State of North
Carolina, and the Federal Government.</td>
<td><p>Ed.D. (2023), NC State</p>
<p>M.S. (2012), UNC</p>
<p>B.S. (2010), UNCW</p></td>
<td>President, January 2023 – Present; VP Student Affairs, UNC 2012 –
2022.</td>
</tr>
<tr class="even">
<td><p><span data-custom-style="Link to Artifact - Resume">Person
Two</span></p>
<p><span
data-custom-style="Link to Artifact - Job Description">Executive Vice
President of Student Affairs</span></p></td>
<td>Provides leadership in a collaborative, supportive environment for
all instructional programs/services, faculty, staff, and students.
Serves as a member of the Executive Team and, in that capacity, provides
support to assigned committees of the Board of Trustees.</td>
<td><p>Ph.D. (2020), NC State</p>
<p>M.S. (2016), UNC</p>
<p>B.S. (2004),</p>
<p>Duke</p></td>
<td>Executive Vice President of Student Affairs, August 2020 – Present;
Dean of General Education July 2016 ­ July 2020.</td>
</tr>
<tr class="odd">
<td><p><span data-custom-style="Link to Artifact - Resume">Person.
Three</span></p>
<p><span data-custom-style="Link to Artifact - Job Description">Vice
President of Business Services CFO</span></p></td>
<td>Responsible for the leadership and management of all functions
associated with the Business Office, Serves as a member of the Executive
Team and ex officio member of the Foundation Board of Directors.</td>
<td>B.S.B.A. (2006), NC State</td>
<td>Vice President of Business Services, July 2006 – Present.</td>
</tr>
<tr class="even">
<td><p><span data-custom-style="Link to Artifact - Resume">Dr. Person
Four</span></p>
<p><span data-custom-style="Link to Artifact - Job Description">Director
of Institutional Research</span></p></td>
<td>Responsible for the data.</td>
<td><p>Ed.D. (2010), NC State</p>
<p>M.A. Ed. (2003), UNC</p>
<p>B.S. (2002), UNC</p></td>
<td>Director of Institutional Research, September 2003 – Present.</td>
</tr>
</tbody>
</table>

### Distance Learning and Off-Campus Instructional Sites

::: {custom-style="Body Text"}
The Director of Instructional Design & Online Learning serves as the
distance and correspondence education coordinator for the College. See
roster above for qualifications.
:::

## Conclusion

::: {custom-style="Body Text"}
The College employs and regularly evaluates administrative and academic
officers with appropriate experience and qualifications to lead the
institution. Therefore, the College is in compliance with this standard.
:::

## Sources

[All sources will be automatically listed here. Do not modify this
section.]{custom-style="Sources"}
